#set page(
  paper: "a4",
  margin: (x: 2.2cm, y: 2.4cm),
  numbering: "1",
)
#set text(font: "New Computer Modern", size: 10.5pt)
#set par(justify: true, leading: 0.62em)
#set heading(numbering: "1.")
#show heading.where(level: 1): it => block(above: 1.4em, below: 0.8em)[
  #set text(size: 14pt, weight: "bold")
  #it
]
#show heading.where(level: 2): it => block(above: 1.0em, below: 0.6em)[
  #set text(size: 11.5pt, weight: "bold")
  #it
]
#show raw.where(block: false): box.with(
  fill: luma(240),
  inset: (x: 3pt, y: 0pt),
  outset: (y: 3pt),
  radius: 2pt,
)
#show raw.where(block: true): block.with(
  fill: luma(245),
  inset: 8pt,
  radius: 4pt,
  width: 100%,
)
#show link: it => underline(text(fill: rgb("#1f4ea1"), it))

#align(center)[
  #text(size: 16pt, weight: "bold")[
    Periodic H#sub[4] V2RDM on MosekTools: \
    Progress on Cutting Variables and Constraints
  ]
  #v(0.3em)
  #text(size: 9.5pt, fill: gray)[
    Repository: `NCTSSoS.jl-h4-periodic-v2rdm-benchmark` #sym.dot.c
    Target system: H#sub[4] periodic, $N_k = 2$, 32 spin-orbitals, 8 active electrons
  ]
]

#v(0.4em)

#block(
  fill: luma(248),
  stroke: (left: 3pt + rgb("#1f4ea1")),
  inset: 10pt,
  radius: 2pt,
)[
  *TL;DR.* We shrank the free-variable count of the V2RDM model by a factor
  of $2.6 times$ and made the model parse cleanly through Mosek's presolve.
  But on a $1$ TiB / $128$-core server, the run still ate $approx 675$ GiB
  of RAM and was killed before a single interior-point iteration. The
  bottleneck is no longer the number of free variables. It is the dense
  affine PSD cones $attach(Q, tl: 2)(D) succ.eq 0$ and
  $attach(G, tl: 2)(D) succ.eq 0$, which Mosek scalarizes into hundreds of
  thousands of affine conic rows. The next move is to drop those dense
  affine PSD blocks and impose them lazily as scalar eigenvector cuts.
]

= Original goal

Solve the periodic H#sub[4] V2RDM relaxation at $N_k = 2$ with the standard
PQG conditions
$
  attach(D, tl: 2) succ.eq 0, quad attach(Q, tl: 2) succ.eq 0, quad attach(G, tl: 2) succ.eq 0,
$
inside the NCTSSoS framework, using `MosekTools.jl` as the conic solver.
The ambient space has $M = 32$ spin-orbitals
($2$ momenta $times$ $2$ spins $times$ $8$ active orbitals) and $8$
electrons. Direct moment-/SOS-based relaxations of the full Hamiltonian are
out of reach; V2RDM is the small relaxation that should plausibly fit.

The earlier baseline was COSMO, which never even printed its banner on this
problem shape. So "make it work on Mosek" is a real engineering target,
not a microbenchmark.

= Step 1 #sym.dash.en D-only moment-basis formulation

We start with the most cone-frugal NCTSSoS formulation:
$
  B_D = {1} union {a_i a_j : i < j},
$
i.e. identity plus the $attach(D, tl: 2)$ pair-annihilator basis #emph[only].
No $attach(Q, tl: 2)$ basis, no $attach(G, tl: 2)$ basis. The reduced Hamiltonian
$attach(K, tl: 2)$ folds the one-body part into the two-body sector, so every
objective monomial is generated by $B_D$.

For 32 spin-orbitals, $binom(32, 2) = 496$ pair rows, plus identity:

#align(center)[
  #table(
    columns: 2,
    align: (left, right),
    stroke: 0.5pt + luma(180),
    inset: 6pt,
    [*Quantity*],                                        [*Count*],
    [Spin-orbital modes $M$],                            [$32$],
    [$attach(D, tl: 2)$ pair rows ($a_i a_j$, $i<j$)],         [$496$],
    [Moment basis size $|B_D|$],                         [$497$],
    [PSD block sizes (by pair momentum $K$)],            [$[256, 240, 1]$],
    [Unique moment-matrix entries],                      [$123\,137$],
    [Total symbolic basis size],                         [$138\,545$],
    [Zero scalar equalities (involution / Wick)],        [$1\,987$],
  )
]

The two large blocks $256$ and $240$ are the $K = 1$ and $K = 0$ sectors of
the pair-momentum decomposition. The $1$ is the identity block.

This is the cheapest the problem ever gets. It does not yet enforce
$attach(Q, tl: 2) succ.eq 0$ or $attach(G, tl: 2) succ.eq 0$.

= Step 2 #sym.dash.en Eliminated PQG formulation (no new variables)

The V2RDM trick: $attach(D, tl: 1)$, $attach(Q, tl: 2)$, $attach(G, tl: 2)$ are #emph[affine]
in $attach(D, tl: 2)$ via the standard fermionic anticommutation identities,
$
  attach(D, tl: 1)_(p s) = 1/(N - 1) sum_q attach(D, tl: 2)_(p q, s q),
$
plus the analogous Q/G constructors. So we keep $attach(D, tl: 2)$ as the only
free Hermitian variable and add $attach(Q, tl: 2)(attach(D, tl: 2)) succ.eq 0$ and
$attach(G, tl: 2)(attach(D, tl: 2)) succ.eq 0$ as #emph[affine] PSD constraints. No
new free variables, just new cones.

#align(center)[
  #table(
    columns: 2,
    align: (left, right),
    stroke: 0.5pt + luma(180),
    inset: 6pt,
    [*Quantity*],                                  [*Count*],
    [Free variable],                               [$attach(D, tl: 2)$ only],
    [Real variables ($240^2 + 256^2$)],            [$123\,136$],
    [$attach(D, tl: 2)$ blocks],                         [$[240, 256]$],
    [$attach(Q, tl: 2)$ blocks],                         [$[240, 256]$],
    [$attach(G, tl: 2)$ blocks],                         [$[512, 512]$],
    [Hermitian PSD blocks (D + Q + G)],            [$[240, 256, 240, 256, 512, 512]$],
    [Scalar equalities (sector + traces)],         [$5$],
    [JuMP constraint objects],                     [$11$],
  )
]

So compared with Step 1 we kept the same $123\,136$ free real variables,
but we now also enforce four extra dense affine Hermitian PSD cones (two
for $attach(Q, tl: 2)$, two for $attach(G, tl: 2)$). That is what V2RDM costs.

= Step 3 #sym.dash.en K-only vs spin-resolved comparison

The K-only blocking above lumps both spins into each pair-momentum sector.
The spin-resolved refinement splits each $K$-block by $2 S_z$ of the pair,
giving smaller but more numerous blocks. This is what the existing
benchmark helper `demos/H4PeriodicNativeV2RDMHelpers.jl` builds.

#align(center)[
  #table(
    columns: 3,
    align: (left, right, right),
    stroke: 0.5pt + luma(180),
    inset: 6pt,
    [*Quantity*],                              [*K-only*],                     [*Spin-resolved*],
    [Free real variables],                     [$123\,136$],                   [$47\,232$],
    [$attach(D, tl: 2)$ block sizes],                [$[240, 256]$],                 [$[56, 128, 56, 64, 128, 64]$],
    [$attach(Q, tl: 2)$ block sizes],                [$[240, 256]$],                 [$[56, 128, 56, 64, 128, 64]$],
    [$attach(G, tl: 2)$ block sizes],                [$[512, 512]$],                 [$[128, 256, 128, 128, 256, 128]$],
    [Hermitian PSD blocks (total)],            [$6$],                          [$18$],
    [Scalar equalities],                       [$5$],                          [$5$],
    [Mosek scalarized matrix vars],            [$approx 250\,000$],            [$94\,960$],
    [Mosek affine conic rows ($Q$ + $G$)],     [#sym.dash.en],                 [$489\,200$],
    [Total real-lift PSD rows (est.)],         [$1\,543\,136$],                [$584\,160$],
  )
]

The spin-resolved refinement removes about
$
  123\,136 \/ 47\,232 approx 2.61 times
$
of the free variables and roughly the same factor of solver-facing PSD rows.
That is the largest pure-structure win we have.

= Step 4 #sym.dash.en MosekTools / server experiment

We ran the spin-resolved eliminated PQG model against MosekTools on a large
shared server, after first verifying both local and remote license loads.

== Run configuration

#align(center)[
  #table(
    columns: 2,
    align: (left, right),
    stroke: 0.5pt + luma(180),
    inset: 6pt,
    [*Setting*],                            [*Value*],
    [Server cores],                         [$128$],
    [Mosek threads (`MSK_IPAR_NUM_THREADS`)], [$64$],
    [Julia threads / BLAS / OMP],           [$1$ each],
    [Total RAM],                            [$approx$ $1.0$ TiB],
  )
]

Mosek did parse the model and printed a summary that matched our predictions:
constraints $approx 47\,733$, affine conic constraints $12$ (totaling
$489\,200$ rows), matrix variables $6$ (scalarized: $94\,960$). It then
entered presolve.

== What happened

#align(center)[
  #table(
    columns: 2,
    align: (left, right),
    stroke: 0.5pt + luma(180),
    inset: 6pt,
    [*Stage*],                                  [*State*],
    [License + load],                           [#text(fill: rgb("#1f7a1f"))[OK]],
    [Conic banner / model summary],             [#text(fill: rgb("#1f7a1f"))[OK]],
    [Presolve started],                         [#text(fill: rgb("#1f7a1f"))[OK]],
    [Initial RSS],                              [$approx$ $236$ GiB],
    [Peak RSS],                                 [$approx$ $675$ GiB],
    [Server RAM used],                          [$approx$ $939 \/ 1024$ GiB],
    [Swap],                                     [full],
    [Interior-point iteration],                 [#text(fill: rgb("#a01f1f"))[never reached]],
    [Outcome],                                  [#text(fill: rgb("#a01f1f"))[OOM-killed]],
  )
]

Reference build cost (just for orientation): the JuMP-side build wall was
$approx$ $57$ s with $approx$ $212$ GiB transient allocations; Mosek's
printed presolve completed in $approx$ $0.04$ s. The expensive work that
ate the remaining hundreds of GiB was the interior-point setup #emph[after]
presolve, not the model build and not the printed presolve step.

= What is stopping us now

It is #emph[not] the number of free variables.

We already dropped from $123\,136$ (K-only) to $47\,232$ (spin-resolved)
without changing the math, and Mosek still ran out of a terabyte of RAM.

The bottleneck is the two #emph[dense affine] PSD cones
$
  attach(Q, tl: 2)(attach(D, tl: 2)) succ.eq 0, quad attach(G, tl: 2)(attach(D, tl: 2)) succ.eq 0.
$
Each entry of $attach(Q, tl: 2)$ and $attach(G, tl: 2)$ is an affine combination of
many $attach(D, tl: 2)$ entries. When MosekTools translates these into
solver-facing form, each Hermitian affine PSD block of size $n$ becomes
$O(n^2)$ affine conic rows, every one of which references many of the
underlying $attach(D, tl: 2)$ scalars. Concretely:

- Affine conic rows for $Q$ + $G$: #h(1em) $489\,200$.
- Scalarized matrix variables for $D$: #h(1em) $94\,960$.
- Total real-lift PSD rows: #h(1em) $584\,160$.

The Schur-complement and KKT factorizations Mosek's interior-point solver
builds on top of that affine map are what blow memory through the roof.
This is consistent with the MOSEK SDP scaling guidance: SDP cost is governed
by PSD cone sizes and affine conic rows, not by JuMP variable count.

So:

#align(center)[
  #table(
    columns: 2,
    align: (left, left),
    stroke: 0.5pt + luma(180),
    inset: 6pt,
    [*Lever pulled*],                                       [*Effect*],
    [Cut free variables ($123\,136 arrow.r 47\,232$)], [Helped, but not enough.],
    [Refine block structure (K $arrow.r$ spin-resolved)], [Helped, but not enough.],
    [Eliminate $attach(D, tl: 1)$, $attach(Q, tl: 2)$, $attach(G, tl: 2)$ as affine in $attach(D, tl: 2)$], [Saves variables, not cone rows.],
    [Add $attach(Q, tl: 2) succ.eq 0$, $attach(G, tl: 2) succ.eq 0$ as dense affine PSD cones], [#text(fill: rgb("#a01f1f"))[Root cause of the OOM.]],
  )
]

= Recommended next direction: lazy Q / G eigenvector cuts

The clean way out is to stop materializing $attach(Q, tl: 2)(D) succ.eq 0$ and
$attach(G, tl: 2)(D) succ.eq 0$ as dense affine PSD constraints inside the JuMP
model, and instead enforce them by separation:

+ #strong[Solve the small model.] Keep $attach(D, tl: 2)$ as the only PSD
  variable. Drop the $attach(Q, tl: 2)$ and $attach(G, tl: 2)$ PSD cones. Keep the
  scalar trace and particle-number equalities.

+ #strong[Numerically check $attach(Q, tl: 2)$, $attach(G, tl: 2)$.] Reconstruct the
  numeric matrices $attach(Q, tl: 2)(attach(D, tl: 2)^star)$ and
  $attach(G, tl: 2)(attach(D, tl: 2)^star)$ from the current solution and compute their
  most-negative eigenvectors $v$.

+ #strong[Add scalar moment-inequality cuts.] For every violating
  eigenvector, add the linear cut
  $ v^dagger attach(Q, tl: 2)(attach(D, tl: 2)) v >= 0, quad
    v^dagger attach(G, tl: 2)(attach(D, tl: 2)) v >= 0, $
  which is one #emph[scalar] inequality on the moments, not a PSD block.

+ #strong[Re-solve and repeat] until no eigenvalue of $attach(Q, tl: 2)$ or
  $attach(G, tl: 2)$ is more negative than a chosen tolerance.

What this trades:

- *Solver-facing rows:* down by orders of magnitude. We replace
  $approx$ $489\,200$ affine conic rows with a handful of scalar inequalities
  per outer iteration.
- *Outer iterations:* up. We pay in the number of separation rounds
  instead of in interior-point memory.
- *Convergence:* not guaranteed in one shot, but well-understood
  cutting-plane behavior; in practice few rounds suffice for V2RDM-shape
  problems.

If we want to stay #emph[inside] the NCTSSoS polynomial-optimization loop
rather than running a hand-rolled JuMP loop, we will need a small framework
extension: support for scalar moment inequality cuts of the form
$chevron.l p\, m chevron.r >= 0$ for an arbitrary polynomial $p$ in the
moments, without forcing those into a localizing-matrix PSD block. That
extension is much smaller than the cost of trying to fit dense affine
$Q$/$G$ PSD cones into Mosek for this problem size.

= Bottom line

#block(
  fill: luma(248),
  stroke: (left: 3pt + rgb("#1f4ea1")),
  inset: 10pt,
  radius: 2pt,
)[
  - Variable-count reduction: #strong[done.]
    $123\,136 arrow.r 47\,232$ free real variables, $2.61 times$ smaller,
    with no change in mathematical content.
  - Block-structure refinement: #strong[done.]
    $6$ Hermitian PSD blocks $arrow.r$ $18$ smaller blocks; total real-lift
    PSD rows roughly $1.54 times 10^6 arrow.r 5.84 times 10^5$.
  - Solver engagement: #strong[done.] Mosek parses the model and finishes
    presolve cleanly. COSMO still cannot do this.
  - Solve completion: #strong[blocked.] Dense affine $Q$/$G$ PSD cones
    drive interior-point setup memory past $1$ TiB on a real server.
  - Next step: #strong[separation loop with scalar eigenvector cuts on
    $Q$ and $G$], not a bigger machine and not a different solver on the
    same dense formulation.
]
